version: '3'

services:
  emp-mysql:
    image: emp-mysql
    build:
      context: ./resources/mysql/
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    healthcheck:
      test: "/etc/init.d/mysql status"
      interval: 2s
      retries: 10
  
  emp-api:
    image: quarkus/employee-api
    build: .
    #depends_on:
    #  emp-mysql:
    #    condition: service_healthy
    ports:
      - 8080:8080
    links:
      - emp-mysql